[package]
name = "sumcheck"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
ark-std = "0.5.0"
criterion = "0.5.1"
digest = "0.10.7"
rand_chacha = "0.9.0"
sha2 = "0.10.8"
sha3 = "0.10.8"
polynomials = { path = "../polynomials"}
